Add GROQ extensions
sanity-io/GROQ pull request #52
Opened 2021-03-17 12:43 UTC by j33ty

2021-03-18 21:08 UTC, atombender requested changes
Almost perfect! 🙂 But I think we need to be a little more precise about how we define the semantics of the geometrics/geographic functionality. I've included some suggestions.

2021-03-18 21:08 UTC, atombender commented on spec/Section 13 -- Extensions.md
> +It takes in two geo point arguments and returns true if first geo value intersects the second one, that is polygon created by first geo value intersects with or contains atleast one of the edge repre
```suggestion
This function takes two geo values, and returns true if they intersect in a planar (non-spherical) coordinate system. The arguments can be any geo values. A geo value intersects with another if it shares any geometric points with the second value; for example, a line crossing a polygon.
```

2021-03-18 21:08 UTC, atombender commented on spec/Section 13 -- Extensions.md
> +* Let {distance} be the [HaverSine distance](https://en.wikipedia.org/wiki/Haversine_formula) between {first} and {second}:
```suggestion
* Let {distance} be the geographic distance between {first} and {second}:
```

2021-03-18 21:08 UTC, atombender commented on spec/Section 13 -- Extensions.md
> +It accepts two Geo Points or GeoJSON Points and returns the distance in meters. Lines/Polygons are not supported.
```suggestion
This functions accepts two geo values, which must be point values, and returns the distance in meters. While exact algorithm is implementation-defined — for example, it may use the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) — it should use as close an approximation to a real Earth distance as possible.
```

2021-03-18 21:08 UTC, atombender commented on spec/Section 6 -- Simple expressions.md
> +* Let {func} be the function defined under the name {name} in either {namespace} namespace if provided, or "global" namespace.
```suggestion
* Let {func} be the function defined under the name {name} in either {namespace} namespace if provided, or the `global` namespace.
```

2021-03-18 21:08 UTC, atombender commented on spec/Section 6 -- Simple expressions.md
> +* If there is no function named {name} defined in either {namespace} namespace if provided, or  or "global" namespace:
```suggestion
* If there is no function named {name} defined in either {namespace} namespace if provided, or  the `global` namespace:
```

2021-03-19 10:56 UTC, j33ty commented
Thanks for the detailed review. I have included _all_ the suggestions in the next commit.

2021-03-19 13:53 UTC, atombender approved these changes

2021-03-19 15:55 UTC, judofyr commented on spec/Section 13 -- Extensions.md
> +  * Return {null}.
This doesn't need to be handled here since it's already done by `global::ptValidate`.

2021-03-19 15:55 UTC, judofyr commented on spec/Section 13 -- Extensions.md
> +Returns true if first geo argument completely contains the second one, using a planar (non-spherical) coordinate system. The first geo argument can be any geo value. The second must be a GeoJSON `Pol
> The second must be a GeoJSON `Polygon` or `MultiPolygon`.

I think that both values can be of either type, although some of the are that useful (e.g. a `Point` will only contain a `Point` if it's the exact same).

2021-03-23 14:07 UTC, merged