Group functions by namespaces.
sanity-io/GROQ pull request #53
Opened 2021-03-23 15:16 UTC by j33ty

2021-03-23 16:43 UTC, atombender requested changes
LGTM, except the string thing.

2021-03-23 16:43 UTC, atombender commented on spec/Section 10 -- Functions.md
> -## lower
We'll need to keep these in the global namespace.

2021-04-07 08:40 UTC, j33ty commented on spec/Section 10 -- Functions.md
> -## lower
Yes, we will have to intro string namespace in a new GROQ spec version (now that we have spec versioning).

2021-04-07 08:45 UTC, judofyr approved these changes
LGTM!

2021-04-07 08:46 UTC, merged