Document array and math functions
sanity-io/GROQ pull request #82
Opened 2022-06-15 15:31 UTC by atombender

Documents `array::unique()`, `math::avg()`, `math::min()`, `math::max()`, `math::sum()`.

2022-06-16 05:52 UTC, sgulseth requested changes

2022-06-16 05:52 UTC, sgulseth commented on spec/Section 10 -- Functions.md
> +    - Increment {count}.
```suggestion
  - Otherwise:
    - Increment {count}.
    - let {n} be the sum of {elem} and {n}.
```

2022-06-16 05:52 UTC, sgulseth commented on spec/Section 10 -- Functions.md
> +    - If {max} is {null} or {elem} is lower than {max}:
```suggestion
    - If {max} is {null} or {elem} is more than {max}:
```

2022-06-16 09:22 UTC, sgulseth approved these changes

2022-07-01 07:28 UTC, judofyr requested changes

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +    - Append {elem} to {output}.
This should refer to https://sanity-io.github.io/GROQ/draft/#sec-Equality to clarify exactly what we mean by "is not in". This would also remove the special case of "is not a primitive" (since `[] != []`).

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +separately unique. For example, `array::unique([[1], [1]])` should return `[[1], [1]]`.
I don't think we need to define "primitive values" here as this behavior is already defined under https://sanity-io.github.io/GROQ/draft/#sec-Equality.

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +    - Append {elem} to {output}.
How about something like this to clarify that the order is not guaranteed?

```suggestion
    - Add {elem} into {output} (at any position).
```

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +- Let {arr} be the result of {Evaluate(strNode, scope)}.
```suggestion
- Let {arr} be the result of {Evaluate(arrNode, scope)}.
```

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +- Let {arr} be the result of {Evaluate(strNode, scope)}.
```suggestion
- Let {arr} be the result of {Evaluate(arrNode, scope)}.
```

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +- Let {arr} be the result of {Evaluate(strNode, scope)}.
```suggestion
- Let {arr} be the result of {Evaluate(arrNode, scope)}.
```

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +    - If {max} is {null} or {elem} is higher than {max}:
```suggestion
    - If {max} is {null} or {PartialCompare(elem, max)} is {Greater}:
```

2022-07-01 07:28 UTC, judofyr commented on spec/Section 10 -- Functions.md
> +    - If {min} is {null} or {elem} is lower than {min}:
```suggestion
    - If {min} is {null} or {PartialCompare(elem, min)} is {Less}:
```

2022-07-04 09:40 UTC, atombender commented on spec/Section 10 -- Functions.md
> +separately unique. For example, `array::unique([[1], [1]])` should return `[[1], [1]]`.
Good points. Updated.

2022-07-18 13:19 UTC, merged