Improve specification of selectors
sanity-io/GROQ pull request #84
Opened 2022-08-03 13:58 UTC by judofyr

- Fully describe the syntax
- Fully describe the search/evaluation semantic
- Fix usage in changedAny/changedOnly

I _think_ this is correct now. I think I want to take a second look later to double-check everything 😅

2022-08-03 14:01 UTC, judofyr commented
(Fixed formatting and force-pushed)

2022-08-04 08:14 UTC, sgulseth requested changes

2022-08-04 08:14 UTC, sgulseth commented on spec/Section 3 -- Execution.md
> +        - Append {keyPath} to {result}.
Combined key path? 🤔

2022-08-04 08:14 UTC, sgulseth commented on spec/Section 3 -- Execution.md
> +          - Append {keyPath} to {result}.
Same as above

2022-08-04 08:14 UTC, sgulseth commented on spec/Section 3 -- Execution.md
> +      - If {innerValue} is an array:
What if it's not an array(or other types assumed below), should the spec cover errors or let that be up to the impl?

2022-08-04 11:57 UTC, judofyr commented on spec/Section 3 -- Execution.md
> +      - If {innerValue} is an array:
It shouldn't cause any error at all. It should just _not_ match up.

2022-08-04 11:58 UTC, judofyr commented on spec/Section 3 -- Execution.md
> +        - Append {keyPath} to {result}.
Yes. Fixed in force-push.

2022-08-04 11:58 UTC, judofyr commented on spec/Section 3 -- Execution.md
> +          - Append {keyPath} to {result}.
Yes. Fixed in force-push.

2022-08-05 10:50 UTC, sgulseth commented on spec/Section 3 -- Execution.md
> +      - If {innerValue} is an array:
✨

2022-08-05 10:50 UTC, sgulseth approved these changes

2022-08-05 10:50 UTC, sgulseth approved these changes

2022-08-08 11:02 UTC, codebymatt approved these changes
Nice work! I have a suggestion and a question, but neither are worth blocking.

2022-08-08 11:02 UTC, codebymatt commented on spec/Section 3 -- Execution.md
> +          - Let {nestedScope} be the result of {NewNestedScope(value, scope)}.
What is `NewNestedScope`? Is it defined elsewhere in the spec?

2022-08-08 11:32 UTC, judofyr commented on spec/Section 3 -- Execution.md
> +          - Let {nestedScope} be the result of {NewNestedScope(value, scope)}.
Yup, it's here: https://sanity-io.github.io/GROQ/draft/#NewNestedScope()

2022-08-08 11:46 UTC, judofyr commented on spec/Section 13 -- Extensions.md
> +- Let {beforeKeyPaths} be the result of {EvaluateSelector(selector, before, scope)}.
Done!

2022-08-08 11:46 UTC, merged