Fix various typos and formatting
sanity-io/GROQ pull request #90
Opened 2022-08-11 14:38 UTC by judofyr

- Fix various typos.
- Use `example` code blocks.
- spec-md doesn't support "::" in the middle of an identity which means that these sections weren't handled as "algorithms". This changes it to use _ as delimiter instead which means that they get properly linked, referenced and appears in the index.

2022-08-11 15:13 UTC, atombender requested changes
Could we fix spec-md to support `::`? It looks pretty ugly (and technically incorrect) to have to use underscores. Maybe we could use a special character (triple underscores?) and then `sed` during build?

2022-08-11 15:13 UTC, atombender commented on spec/14-extensions.md
> +diff_changedAny(args):
Should this not have `_validate`? See also the other ones.

2022-08-11 15:14 UTC, atombender commented
I noticed a "prettier-ignore" in the middle of the spec, maybe we can fix that:

![Screen Shot 2022-08-11 at 17 14 29](https://user-images.githubusercontent.com/50314/184167844-4e597d39-33bc-495b-9aef-9cc3fbd5f2ce.jpg)

2022-08-12 07:55 UTC, judofyr commented
> Could we fix spec-md to support `::`? It looks pretty ugly (and technically incorrect) to have to use underscores. Maybe we could use a special character (triple underscores?) and then `sed` during build?

I already requested it https://github.com/leebyron/spec-md/issues/83, but it hasn't got any traction. I'd rather not fork spec-md. It's not too bad IMO, these identifiers are only for referring to the implementation internally in the spec.

2022-08-12 08:01 UTC, judofyr commented
I've fixed the prettier-ignore (in not a very clean way) and fixed the `validate` functions.

2022-08-12 08:48 UTC, atombender approved these changes

2022-08-12 08:54 UTC, merged